# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Hello World'
  app.provisioning_profile = '/Users/Alan/Library/MobileDevice/Provisioning Profiles/iOS_Team_Provisioning_Profile_.mobileprovision'
end
